#!/bin/bash

set -ex

ROOT_DIR=$(cd $(dirname $(dirname $0)) && pwd)
OUT_DIR=$ROOT_DIR/out

build() {
    local os=$1
    local arch=$2
    local postfix=$3

    GOOS=$os GOARCH=$arch $ROOT_DIR/scripts/build
    nf="ascli.$postfix"
    if [ "$os" == "windows" ]; then
            nf="$nf.exe"
    fi
    
    mv $OUT_DIR/ascli "$OUT_DIR/$nf"
}

build darwin amd64 osx
build linux amd64 linux64
build linux arm64 linux_arm64
build linux 386 linux32
build windows amd64 win64
build windows 386 win32
